config/routes.rb
Rails.application.routes.draw do

  root 'characters#index'

  get 'welcome/index'

  resources :characters do
    resources :episodes do
      member do
        post 'add_to_episode'
        delete 'remove_from_episode'
      end
    end
  end

  resources :episodes

end

app/models/character.rb
class Character < ActiveRecord::Base

  has_and_belongs_to_many :episodes

end

app/models/episode.rb
class Episode < ActiveRecord::Base

  has_and_belongs_to_many :characters

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @characters = Character.all.order(:name)
    @autobots = Character.where(affiliation: 'Autobot').order(:name)
    @dinobots = Character.where(affiliation: 'Dinobot').order(:name)
  end

  def show
    @character = Character.find(params[:id])
    @miniseries = Episode.where(season: 'Miniseries').order(:episode)
    @seasonOne = Episode.where(season: '1').order(:episode)
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)

    if @character.save
      redirect_to @character
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    if @character.update!(character_params)
      redirect_to @character
    else
      render :edit
    end
  end

  def destroy
    @character = Character.find(params[:id])
    if @character.destroy
      redirect_to characters_path
    end
  end

  private
    def character_params
      params.require(:character).permit(:name, :title, :bio, :affiliation, :image)
    end

end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @miniseries = Episode.where(season: 'Miniseries').order(:episode)
    @seasonOne = Episode.where(season: '1').order(:episode)
  end

  def show
    @episode = Episode.find(params[:id])
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
    def episode_params
      params.require(:episode).permit(:name, :season, :episode)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/edit.html.erb
<section>
  <h1>Edit Character</h1>

  <div class="character-form">
    <%= form_for @character do |f| %>
      <p>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :bio %><br />
        <%= f.text_area :bio %>
      </p>

      <p>
        <%= f.label :image %><br />
        <%= f.text_field :image %>
      </p>

      <p>
        <%= f.submit %>
      </p>

    <% end %>
  </div>

  <%= link_to 'Delete', character_path(@character), method: :delete, class: 'edit' %>

</section>

app/views/characters/index.html.erb
<section>

  <div class="section-title-search">
    <h1>Characters</h1>
    <form id="search-bar">
      <input type="text" placeholder="Search" />
    </form>
  </div>

  <div class="new-entry-container">
    <div>
      <%= link_to(new_character_path) do %>
      <div>
        <p>Add Character <i class="fa fa-plus" aria-hidden="true"></i></p>
      </div>
      <% end %>
    </div>
  </div>

  <div class="characters-container">
    <span>
      <h2>Autobots</h2>
    </span>
    <div>
      <% @autobots.each do |character| %>
        <div class="character-portrait">
          <%= link_to character do %>
            <%= image_tag character.image, class: "character-image" %>
            <p><%= character.name %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="characters-container">
    <span>
      <h2>Dinobots</h2>
    </span>
    <div>
      <% @dinobots.each do |character| %>
        <div class="character-portrait">
          <%= link_to character do %>
            <%= image_tag character.image, class: "character-image" %>
            <p><%= character.name %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/characters/new.html.erb
<section>
  <h1>New Character</h1>

  <div class="character-form">
    <%= form_for @character do |f| %>
      <p>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :title %><br />
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :bio %><br />
        <%= f.text_area :bio %>
      </p>

      <p>
        <%= f.label :image %><br />
        <%= f.text_field :image %>
      </p>

      <p>
        <%= f.submit %>
      </p>

    <% end %>
  </div>
</section>

app/views/characters/show.html.erb
<section>

  <div class="breadcrumbs">
    <%= link_to characters_path do %>
        <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
        <span>All Characters</span>
    <% end %>
  </div>
  <div class="character-show-top">
    <div id="character-bio-left"><img src="<%= @character.image %>" alt="Character image" /></div>
    <div id="character-bio-right">
      <div>
        <div>
          <h2><%= @character.name %></h2>
        </div>
        <img src="http://i.imgur.com/72O1YYR.png" alt="box-end" />
      </div>
      <div>
        <h4><%= @character.affiliation %>  // </h4>
        <h3><%= @character.title %></h3>
      </div>
      <p><%= @character.bio %></p>
    </div>
  </div>

  <div class="appearances-container">
    <h3>Appearances</h3>

    <h2 class="episode-subtitle">The Miniseries</h2>

    <div class="season-container">
      <% @miniseries.each do |episode| %>
        <div class="episode-box">
          <%= link_to episode do %>
            <div></div>
          <% end %>
        </div>
      <% end %>
    </div>

    <h2 class="episode-subtitle">Season One</h2>

    <div class="season-container">
      <% @seasonOne.each do |episode| %>
        <div class="episode-box">
          <%= link_to episode do %>
            <div></div>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <%= link_to 'Edit', edit_character_path(@character) %>

</section>

app/views/episodes/index.html.erb
<section class="section-episodes">

  <div class="section-title-search">
    <h1>Episodes</h1>
    <form id="search-bar">
      <input type="text" placeholder="Search" />
    </form>
  </div>

  <div class="new-entry-container">
    <div>
      <%= link_to(new_episode_path) do %>
      <div>
        <p>Add Episode <i class="fa fa-plus" aria-hidden="true"></i></p>
      </div>
      <% end %>
    </div>
  </div>


  <h2 class="episode-subtitle">The Miniseries</h2>

  <div class="season-container">
    <% @miniseries.each do |episode| %>
      <div class="episode-box">
        <%= link_to episode do %>
          <div></div>
        <% end %>
      </div>
    <% end %>
  </div>

  <h2 class="episode-subtitle">Season One</h2>

  <div class="season-container">
    <% @seasonOne.each do |episode| %>
      <div class="episode-box">
        <%= link_to episode do %>
          <div></div>
        <% end %>
      </div>
    <% end %>
  </div>

</section>

app/views/episodes/show.html.erb
<%= @episode.name %>
<%= @episode.season %>
<%= @episode.episode %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>G1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic|Roboto:300,300italic,400,100,100italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-aNUYGqSUL9wG/vP7+cWZ5QOM4gsQou3sBfWRr/8S3R1Lv0rysEmnwsRKMbhiQX/O" crossorigin="anonymous">
</head>
<body>
  <div id="body-background">

    <nav>
      <%= link_to(characters_path) do %>
        <div id="nav-left">
          <h1>G1</h1>
          <h2>Transformers <br /> Database</h2>
        </div>
      <% end %>
      <div id="nav-right">
        <%= link_to(characters_path) do %>
          <span>Characters</span>
        <% end %>
        <%= link_to(episodes_path) do %>
          <span>Episodes</span>
        <% end %>
        <span>About</span>
        <span>Login</span>
      </div>
    </nav>

    <%= yield %>

    <footer>
      <div>
      </div>
    </footer>

  <!-- // Body's background image -->
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<section>
  <h1>Welcome#Index</h1>
</section>